### ISSUE TITLE
Change the syntax of themes/nodebb-theme-persona/templates/partials/topics_list.tpl from JS to benchpressjs

### ISSUE THREAD

**Issue by LujainAlMansoori** [CMU-17313Q/fall23-nodebb-inshallah-a#48]
Description: The If conditions that were in javascript are not working. These if conditions are not passing because they are in the wrong language, these have to be updated in themes/nodebb-theme-persona/templates/partials/topics_list.tpl from javascript to benchpressjs. 

Estimated effort: This would require little effort because the foundation (all the if conditions and logic) is already there. However, they just need to be translated to benchpressjs. 

Dependencies: This works with issue #39 

Acceptance criteria: If the private posts appear only in the instructor's account and the owner's account this means that the conversion from JS to benchpressjs worked. Also, the conversion of the anonymous statements also apply, if the anonymous posts show up as anonymous in other user's accounts (not the instructor or owner), then it would have worked. This could be done through testing the return of the topics list.

**Comment by mbfannan** [comment]
Great job!
