### ISSUE TITLE
Create the backend logic for isResolved by adding an attribute to a topic

### ISSUE THREAD

**Issue by LujainAlMansoori** [CMU-17313Q/fall23-nodebb-inshallah-a#68]
Description: This involves connecting the "Urgent" button in the front-end to the isUrgent attribute in the backend, specifically to the topic object. 

Estimated effort: This effort would be easy since the existing infrastructure for the topic already exists.

Dependencies: This issue has no dependencies. 

Acceptance criteria: The topic object needs to have an isUrgent attribute included in it, this has to be reflected in the /api (when we showcase the topic object in the api to check the return objects of all the database).

**Comment by mbfannan** [comment]
Resolved by pull request #72 .
